env:
  es6: true
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'
  - 'plugin:lodash-fp/recommended'

rules:
  no-console: 0
